server:
  port: 9195
  servlet.context-path: /security
  undertow.max-http-post-size: 0

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.FilterChainProxy: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO

spring:
  application.name: security
  main.allow-bean-definition-overriding: true
  profiles:
    active: dev
  jackson.default-property-inclusion: non_absent
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        #        generate_statistics: true
        jdbc:
          batch_size: 1000
          time_zone: UTC
        order_inserts: true
        order_updates: true
        #        batch_versioned_data: true
        use-new-id-generator-mappings: true
  #    open-in-view: false
  datasource:
    url: jdbc:mariadb://localhost:3308/sakila
    username: root
    password: 123456

app.jwt.secret: bezKoderSecretKey
app.jwt.expiration: 86400000